#                                 GLOBAL CONFIGURATION
# =====================================================================================
experiment_name: "Vitiscan_CNN"
project_version: "1.0"

# ---- Data configuration ---
data:
  root_dir: '../data'
  num_classes: 7
  train_split: 0.8
  validation_split: 0.1
  test_split: 0.1

# --- Default training hyperparameters ---
default_training:
  optimizer: "Adam"
  loss_function: "CrossEntropyLoss"
  batch_size: 32
  epochs: 40
  learning_rate: 0.0001

  # weight_decay: 0.0001 # L2 Regularization
  # scheduler_patience: 5 # To reduce the learning rate if the validation process is stalled
  # early_stopping_patience: 10 # To stop the training if the validation process is stalled


#                                    MODELS TO RUN
# =====================================================================================

models_to_run:

  # --- ResNets ---
  - name: "resnet18"
    input_size: 224
    freeze_base: True
    description: "ResNet-18, Transfer learning (baseline)"

  - name: "resnet18"
    input_size: 224
    freeze_base: false
    unfreeze_layer: "layer4"
    description: "ResNet-18, Fine-tuning (for comparison)"
    
  - name: "resnet34"
    input_size: 224
    freeze_base: True
    description: "ResNet-34, Transfer learning (deeper architecture)"


  # --- EfficientNets ---
  - name: "efficientnet_b0"
    input_size: 224
    freeze_base: False
    learning_rate: 0.00005
    description: "EfficientNet B0, Fine-Tuning (different architecture)"


# Models below require GPU or longer training time
 
#  # --- ResNets ---
#   - name: "resnet50"
#     input_size: 224
#     freeze_base: False
#     learning_rate: 0.00005
#     description: "ResNet-50, Fine-tuning"

#  # --- EfficientNets ---
#   - name: "efficientnet_b1"
#     input_size: 240 # Recommanded size
#     freeze_base: False
#     learning_rate: 0.00005
#     description: "EfficientNet B1, Fine-Tuning"

#   - name: "efficientnet_b2"
#     input_size: 260  # Recommanded size
#     freeze_base: False
#     learning_rate: 0.00005
#     description: "EfficientNet B2, Plus performant, Fine-Tuning"
    
#   # --- MobileNet ---
#   - name: "mobilenet_v2"
#     input_size: 224
#     freeze_base: True 
#     description: "MobileNetV2, Trasnfer learning"


 