name: vitiscan_cnn
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - pip:
    - huggingface_hub
  
  # PyTorch with CUDA
  - pytorch>=2.5.0
  - torchvision>=0.20.0
  - torchaudio>=2.5.0
  
  # MLflow and tracking
  - mlflow=3.7.0
  - tensorboard>=2.18.0
  - protobuf>=5.29.0
  - cloudpickle>=3.1.0
  - pyarrow>=18.0.0
  
  # ML utilities and optimization
  - shap>=0.46.0
  - optuna>=4.1.0
  
  # AWS for MLFlow
  - boto3==1.35.79
  - s3fs==2025.12.0

  # Scientific dependancies
  - numpy>=1.26.0
  - pandas>=2.2.0
  - scikit-learn>=1.5.0
  
  # Visualization
  - matplotlib>=3.9.0
  - plotly==5.24.0
  - seaborn>=0.13.0
  
  # Utils
  - pyyaml>=6.0
  - tqdm>=4.66.0
  - pillow>=10.0.0
  - requests>=2.31.0
  - torchinfo==1.8.0
  - python-dotenv
  
  # Jupyter (for notebooks)
  - notebook
  - ipykernel
  - ipywidgets

